from fastapi import FastAPI, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List
from .worker import process_task_background
from . import models, schemas, database, redis_client
from fastapi.middleware.cors import CORSMiddleware

# Create the database tables in Postgres automatically on startup
models.Base.metadata.create_all(bind=database.engine)

app = FastAPI(title="Distributed Task Monitor")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allows all origins for development
    allow_credentials=True,
    allow_methods=["*"],  # Allows POST, GET, DELETE, etc.
    allow_headers=["*"],
)

@app.get("/")
def home():
    return {"status": "Online", "message": "The Task Monitor is breathing"}

# POST route to create a task
@app.post("/tasks/", response_model=schemas.Task)
def create_task(task: schemas.TaskCreate, db: Session = Depends(database.get_db)):
    db_task = models.Task(**task.model_dump())
    db.add(db_task)
    db.commit()
    db.refresh(db_task)
    
    process_task_background.delay(db_task.id)
    return db_task

# GET route for a single task + Redis counter
@app.get("/tasks/{task_id}", response_model=schemas.Task)
def read_single_task(task_id: int, db: Session = Depends(database.get_db)):
    db_task = db.query(models.Task).filter(models.Task.id == task_id).first()
    if not db_task:
        raise HTTPException(status_code=404, detail="Task not found")
    
    # Use the client we defined in redis_client.py
    redis_client.redis_client.incr(f"task_views:{task_id}")
    
    return db_task

# GET route to see the count from Redis
@app.get("/tasks/{task_id}/views")
def get_task_views(task_id: int):
    # This hits the RAM-based Redis, not the disk-based Postgres
    views = redis_client.redis_client.get(f"task_views:{task_id}")
    return {"task_id": task_id, "views": views or 0}

@app.get("/tasks/", response_model=List[schemas.Task])
def read_all_tasks(db: Session = Depends(database.get_db)):
    return db.query(models.Task).all()

@app.delete("/tasks/")
def delete_all_tasks(db: Session = Depends(database.get_db)):
    db.query(models.Task).delete()
    db.commit()
    return {"message": "All tasks deleted"}


@app.post("/tasks/bulk", response_model=List[schemas.Task])
def create_bulk_tasks(db: Session = Depends(database.get_db)):
    created_tasks = []
    for i in range(1, 5):
        new_task = models.Task(
            title=f"Bulk Task #{i}",
            description="Generated by bulk create",
            is_urgent=False
        )
        db.add(new_task)
        db.commit()
        db.refresh(new_task)
        
        # Send each one to a background worker
        process_task_background.delay(new_task.id)
        created_tasks.append(new_task)
        
    return created_tasks